CREATE TABLE author
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    uco  VARCHAR(255),
    type VARCHAR(255),
    CONSTRAINT pk_author PRIMARY KEY (id)
);

CREATE TABLE department
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    org_unit        VARCHAR(255),
    department_name VARCHAR(255),
    CONSTRAINT pk_department PRIMARY KEY (id)
);

CREATE TABLE project
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    proj_id              VARCHAR(255),
    reg_code             VARCHAR(255),
    title                TEXT                                    NOT NULL,
    author_id            BIGINT,
    state                VARCHAR(255),
    date_begin           BYTEA,
    date_end             BYTEA,
    muni_role            VARCHAR(255),
    investor             VARCHAR(255),
    department_id        BIGINT,
    annotation           TEXT,
    processed_annotation TEXT,
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE role
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    user_id BIGINT,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    jwt_identifier VARCHAR(255)                            NOT NULL,
    uco            VARCHAR(255)                            NOT NULL,
    name           VARCHAR(255),
    email          VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE author
    ADD CONSTRAINT uc_author_uco UNIQUE (uco);

ALTER TABLE users
    ADD CONSTRAINT uc_users_jwtidentifier UNIQUE (jwt_identifier);

ALTER TABLE users
    ADD CONSTRAINT uc_users_uco UNIQUE (uco);

ALTER TABLE project
    ADD CONSTRAINT FK_PROJECT_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES author (id);

ALTER TABLE project
    ADD CONSTRAINT FK_PROJECT_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE role
    ADD CONSTRAINT FK_ROLE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);