FROM node:lts-alpine as build

COPY web-app /web-app
WORKDIR web-app

RUN yarn
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL $REACT_APP_API_URL
RUN yarn build

FROM nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /web-app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]